name = "timesweeper-api"
main = "src/worker.ts"
compatibility_date = "2026-02-25"

[durable_objects]
bindings = [{ name = "EVENT_ROOMS", class_name = "EventRoom" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["EventRoom"]

[vars]
ALLOW_LOCALHOST_ORIGIN = "false"

[env.dev.vars]
ALLOW_LOCALHOST_ORIGIN = "true"

[env.dev.durable_objects]
bindings = [{ name = "EVENT_ROOMS", class_name = "EventRoom" }]
